/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PlayInfoController;

/**
 *
 * @author dimi44
 */
public class playInfo extends javax.swing.JFrame {
    boolean fav;
    String name;
    String iconName;
    String show;
    String scheduleId;
    String title;
    String userDetails[];
    /**
     * Creates new form playInfo
     */
    public playInfo(String userDetail[],String show) {
        initComponents();
        this.userDetails=userDetail;
        this.name=userDetail[0];
        usernameLbl.setText(name);
        this.show=show;
        showInfo(show);
        checkFavs();
        
    }
    
    private void checkFavs(){
        
       int check= PlayInfoController.checkFavorites(name, title);
        if(check==2){
            addFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconmonstr-favorite-9-48.png")));
            fav=false;
            }
        else if(check==1){
            addFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconmonstr-favorite-12-48.png")));
            fav=true;
        }else{
            //todo label show ERROR
        }
        
        
    }
    private playInfo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        showfav = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        ads = new javax.swing.JLabel();
        genre = new javax.swing.JLabel();
        playNamelbl2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        addFav = new javax.swing.JButton();
        titleLbl1 = new javax.swing.JLabel();
        genreLbl1 = new javax.swing.JLabel();
        schfDate = new javax.swing.JLabel();
        playNamelbl5 = new javax.swing.JLabel();
        genreLbl2 = new javax.swing.JLabel();
        titleLbl2 = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        genreLbl = new javax.swing.JLabel();
        schDateLbl = new javax.swing.JLabel();
        schTimeLbl = new javax.swing.JLabel();
        durationLbl = new javax.swing.JLabel();
        producedLbl = new javax.swing.JLabel();
        actorNmLbl = new javax.swing.JLabel();
        actorSrnLbl = new javax.swing.JLabel();
        titleLbl3 = new javax.swing.JLabel();
        roleLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        usernameLbl.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        usernameLbl.setText("username");
        usernameLbl.setPreferredSize(new java.awt.Dimension(100, 15));

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        showfav.setBackground(new java.awt.Color(20, 32, 37));
        showfav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/favorite-154756_640.png"))); // NOI18N
        showfav.setOpaque(false);
        showfav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showfavActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showfav, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(showfav, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(20, 32, 37));
        jPanel2.setPreferredSize(new java.awt.Dimension(1401, 700));

        img.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        img.setOpaque(true);

        ads.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ads.setForeground(new java.awt.Color(255, 255, 255));
        ads.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ads.setText("Title :");

        genre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genre.setForeground(new java.awt.Color(255, 255, 255));
        genre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genre.setText("Genre :");

        playNamelbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playNamelbl2.setForeground(new java.awt.Color(255, 255, 255));
        playNamelbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playNamelbl2.setText("Duration (mins) :");

        backButton.setBackground(new java.awt.Color(20, 32, 37));
        backButton.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back To The Schedule");
        backButton.setMargin(new java.awt.Insets(5, 14, 5, 14));
        backButton.setOpaque(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addFav.setBackground(new java.awt.Color(20, 32, 37));
        addFav.setForeground(new java.awt.Color(255, 255, 255));
        addFav.setOpaque(false);
        addFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFavActionPerformed(evt);
            }
        });

        titleLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLbl1.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleLbl1.setText("Name :");

        genreLbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genreLbl1.setForeground(new java.awt.Color(255, 255, 255));
        genreLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genreLbl1.setText("Play :");
        genreLbl1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        schfDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        schfDate.setForeground(new java.awt.Color(255, 255, 255));
        schfDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        schfDate.setText("Schedule date :");

        playNamelbl5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playNamelbl5.setForeground(new java.awt.Color(255, 255, 255));
        playNamelbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playNamelbl5.setText("Produced :");

        genreLbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genreLbl2.setForeground(new java.awt.Color(255, 255, 255));
        genreLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genreLbl2.setText("Schedule time :");

        titleLbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLbl2.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleLbl2.setText("Surname :");

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLbl.setText("Title :");

        genreLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genreLbl.setForeground(new java.awt.Color(255, 255, 255));
        genreLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genreLbl.setText("Genre :");

        schDateLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        schDateLbl.setForeground(new java.awt.Color(255, 255, 255));
        schDateLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        schTimeLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        schTimeLbl.setForeground(new java.awt.Color(255, 255, 255));
        schTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        durationLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        durationLbl.setForeground(new java.awt.Color(255, 255, 255));
        durationLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        durationLbl.setText("Duration :");

        producedLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        producedLbl.setForeground(new java.awt.Color(255, 255, 255));
        producedLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        producedLbl.setText("Produced :");

        actorNmLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actorNmLbl.setForeground(new java.awt.Color(255, 255, 255));
        actorNmLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        actorNmLbl.setText("Name :");

        actorSrnLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actorSrnLbl.setForeground(new java.awt.Color(255, 255, 255));
        actorSrnLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        actorSrnLbl.setText("Surname :");

        titleLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLbl3.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleLbl3.setText("Role:");

        roleLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        roleLbl.setForeground(new java.awt.Color(255, 255, 255));
        roleLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roleLbl.setText("Surname :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ads, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(playNamelbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(schfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(genreLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(playNamelbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(titleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(genreLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(titleLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(roleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(actorNmLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(actorSrnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(genreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(durationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(schDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(schTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(producedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(52, 52, 52)
                                .addComponent(addFav, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(backButton)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(addFav))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ads)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(schfDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genreLbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(playNamelbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(playNamelbl5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(titleLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genreLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(schDateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(schTimeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(durationLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(producedLbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genreLbl1)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(titleLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titleLbl2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(actorNmLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(actorSrnLbl)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLbl3)
                    .addComponent(roleLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showInfo(String show){
        String[] showPin=PlayInfoController.getInfo(show);
        int i=0;
        while(showPin[i]!=null){
            title=showPin[1];
            img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/"+title+".jpg")));
            titleLbl.setText(showPin[1]);
            genreLbl.setText(showPin[0]);
            producedLbl.setText(showPin[2]);
            actorNmLbl.setText(showPin[3]);
            actorSrnLbl.setText(showPin[4]);
            roleLbl.setText(showPin[5]);
            schTimeLbl.setText(schTimeLbl.getText()+" "+showPin[6+i]);
            schDateLbl.setText(schDateLbl.getText()+" "+showPin[7+i]);
            durationLbl.setText(showPin[8]);
            scheduleId=showPin[9];
            
       
            i=i+10;
        }
    }
    private void showfavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showfavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showfavActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        home newhome=new home();
        newhome.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFavActionPerformed
        if(fav){
            addFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconmonstr-favorite-9-48.png")));
            fav=false;
             PlayInfoController.deleteFavorites(name, title);   
            }
        else{
            addFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconmonstr-favorite-12-48.png")));
            fav=true;
           PlayInfoController.addFavorites(name,title);
            }
    }//GEN-LAST:event_addFavActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        mainPage main=new mainPage(userDetails);
        main.setVisible(true);

    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actorNmLbl;
    private javax.swing.JLabel actorSrnLbl;
    private javax.swing.JButton addFav;
    private javax.swing.JLabel ads;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel durationLbl;
    private javax.swing.JLabel genre;
    private javax.swing.JLabel genreLbl;
    private javax.swing.JLabel genreLbl1;
    private javax.swing.JLabel genreLbl2;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel playNamelbl2;
    private javax.swing.JLabel playNamelbl5;
    private javax.swing.JLabel producedLbl;
    private javax.swing.JLabel roleLbl;
    private javax.swing.JLabel schDateLbl;
    private javax.swing.JLabel schTimeLbl;
    private javax.swing.JLabel schfDate;
    private javax.swing.JButton showfav;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel titleLbl1;
    private javax.swing.JLabel titleLbl2;
    private javax.swing.JLabel titleLbl3;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
